[staging]
maquina-b ansible_host=10.10.1.20 ansible_user=deploy ansible_password=deploy

[production]
maquina-a ansible_host=10.10.1.10 ansible_user=deploy ansible_password=deploy

[all:vars]
ansible_port=22
ansible_connection=ssh
